basePath: /
definitions:
  constant.AuthRole:
    enum:
    - admin
    - guest
    type: string
    x-enum-varnames:
    - AuthAdmin
    - AuthGuest
  model.CCTVItem:
    properties:
      height:
        type: integer
      id:
        type: string
      latitude:
        type: number
      link:
        type: string
      longitude:
        type: number
      thumbnail:
        type: string
      title:
        type: string
      width:
        type: integer
    type: object
  response.AuthMe:
    properties:
      avatar:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      role:
        $ref: '#/definitions/constant.AuthRole'
    type: object
  response.Base:
    properties:
      data: {}
      message:
        example: Message!
        type: string
    type: object
  response.Home:
    properties:
      author:
        type: string
      github:
        type: string
      linkedin:
        type: string
      title:
        type: string
      website:
        type: string
    type: object
info:
  contact: {}
  description: This is an API documentation of BE Tilik Jalan
  title: BE Tilik Jalan
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Home
      operationId: home
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Base'
            - properties:
                data:
                  $ref: '#/definitions/response.Home'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Base'
      summary: Home based on parameter
      tags:
      - Home
  /auth/google:
    get:
      description: Auth Google Redirection
      operationId: get-auth-google
      responses:
        "307":
          description: Temporary Redirect
        "500":
          description: Internal Server Error
      summary: Get Auth Google Redirection based on parameter
      tags:
      - auth
  /auth/google/callback:
    get:
      description: Auth Google Callback
      operationId: get-auth-google-callback
      responses:
        "307":
          description: Temporary Redirect
        "500":
          description: Internal Server Error
      summary: Get Auth Google Callback based on parameter
      tags:
      - auth
  /auth/me:
    get:
      description: Auth Me
      operationId: get-auth-me
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Base'
            - properties:
                data:
                  $ref: '#/definitions/response.AuthMe'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Base'
            - properties:
                message:
                  type: string
              type: object
      security:
      - AccessToken: []
      summary: Get Auth Me based on parameter
      tags:
      - auth
  /cctv:
    get:
      consumes:
      - application/json
      operationId: get-all-cctv
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Base'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.CCTVItem'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Base'
            - properties:
                message:
                  type: string
              type: object
      security:
      - AccessToken: []
      summary: Get all CCTV records
      tags:
      - cctv
securityDefinitions:
  AccessToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
